### ISSUE TITLE
Question about shutdown connection

### ISSUE THREAD

**Issue by tgiachi** [reinhapa/rabbitmq-cdi#29]
Hi, Is correct this messages, when i showdown the war application?

Thanks

```java
12:21:05,233 WARN  [net.reini.rabbitmq.cdi.ResourceCloser] (AMQP Connection 127.0.0.1:5672) closing channel for consumer class net.reini.rabbitmq.cdi.EventConsumer
12:21:05,233 WARN  [net.reini.rabbitmq.cdi.ConsumerHolderChannelShutdownListener] (AMQP Connection 127.0.0.1:5672) channel shutdown detected: com.rabbitmq.client.ShutdownSignalException: clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQConnection.startShutdown(AMQConnection.java:918)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1038)
```

**Comment by reinhapa** [comment]
Hi  @tgiachi that is normal as we try to clean shutdown all dependent tasks and there is no actual clear indicator for a system being undeployed within the CDI ecosystem  right now..

**Comment by tgiachi** [comment]
@reinhapa thank you!
